port: 3000
address: 0.0.0.0
metrics:
  port: 4000
  address: 0.0.0.0
  user_agent_patterns:
    patterns:
      ios:
        - "Gem.*CFNetwork.*Darwin"
      android:
        - "okhttp/4\\..*"

domains:
  - domain: localhost:3000
    chain_type: ethereum
    poll_interval_seconds: 10
    urls:
      - url: https://eth.llamarpc.com
        headers:
          x-api-key: test
        urls_override:
          "/":
            url: https://rpc.ankr.com/eth
        #headers:
        #  x-api-key: test2
        #
      - url: https://rpc.ankr.com/eth

  - domain: localhost:3002
    chain_type: bitcoin
    urls:
      - url: https://blockbook.btc.zelcore.io

  - domain: localhost:3003
    chain_type: solana
    poll_interval_seconds: 15
    block_delay: 5
    urls:
      - url: https://api.mainnet-beta.solana.com
      - url: https://api.tatum.io/v3/blockchain/node/solana-mainnet
      #- url: https://solana.drpc.org

  - domain: localhost:3004
    chain_type: cosmos
    urls:
      - url: https://cosmos-rest.publicnode.com

  - domain: localhost:3005
    chain_type: ton
    urls:
      - url: https://toncenter.com

  - domain: localhost:3006
    chain_type: tron
    urls:
      - url: https://api.trongrid.io

  - domain: localhost:3007
    chain_type: aptos
    urls:
      - url: https://fullnode.mainnet.aptoslabs.com

  - domain: localhost:3008
    chain_type: sui
    urls:
      - url: https://sui-mainnet-endpoint.blockvision.org

  - domain: localhost:3009
    chain_type: xrp
    poll_interval_seconds: 30
    urls:
      - url: https://s1.ripple.com:51234
      - url: https://s2.ripple.com:51234

  - domain: localhost:3010
    chain_type: near
    poll_interval_seconds: 60
    block_delay: 5
    urls:
      - url: https://rpc.mainnet.near.org
      - url: https://free.rpc.fastnear.com
  
  - domain: localhost:3011
    chain_type: unknown
    poll_interval_seconds: 60
    block_delay: 5
    urls:
      - url: https://rpc.mainnet.near.org