port: 3000
address: 0.0.0.0
domains:
  - domain: localhost:3000
    urls:
      - url: https://eth.llamarpc.com
        headers:
          x-api-key: test
        urls_override:
          "/":
            url: https://rpc.ankr.com/eth
        #headers:
        #  x-api-key: test2
        #
    urls_override:
      "/":
        url: https://cloudflare-eth.com
